---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: poseidon-tsunami
  labels:
    app: poseidon-tsunami
spec:
  replicas: 10
  template:
    metadata:
      name: poseidon-tsunami
      labels:
        app: poseidon-tsunami
        name: poseidon-tsunami-pod
    spec:
      containers:
      - name: poseidon-tsunami
        image: xenokube/poseidon
        command: ["start_stress"]
